#服务的端口号
server:
    port: 8080
    
spring:  
    mvc:  
      view:  
        prefix: /WEB-INF/jsp/  
        suffix: .jsp  
      static-path-pattern: /**
      static-locations : classpath:/static/
    datasource:
        name: test
        url: jdbc:mysql://192.168.0.136:3306/test?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 11
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 200
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis: 
  typeAliasesPackage: model 